services:
  - type: web
    name: Raadaa
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    startCommand: |
      python manage.py migrate &&
      python manage.py createsuperuser --noinput --username admin --password admin@raadaa &&
      gunicorn raadaa.wsgi:application --bind 0.0.0.0:8000 --timeout 120 --workers 2
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: raadaa.settings
      - key: DEBUG
        value: "False"  # Keep True for debugging
      - key: SECRET_KEY
        value: 5p7f1c&0+s(y05#z2)@3r&i4s8$_%#s9!1x(+8&(!i#c4w2
      - key: ALLOWED_HOSTS
        value: raadaa.onrender.com,www.raadaa.onrender.com,localhost
      - key: DATABASE_URL
        fromDatabase:
          name: raadaa
          property: postgresql://admin:3S11nfVdN0IAcabPWkL0W1NMAJDGnZd5@dpg-d0qriabuibrs73eskev0-a.oregon-postgres.render.com/raadaa