services:
  - type: web
    name: Raadaa
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    startCommand: |
      python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      gunicorn raadaa.wsgi
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: raadaa.settings
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        value: your-secret-key
      - key: ALLOWED_HOSTS
        value: raadaa.onrender.com
