# Generated by Django 4.2.21 on 2025-07-02 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_tenantapplication_tenant_admin_tenant_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantapplication',
            name='password',
            field=models.CharField(default=123456, max_length=255),
            preserve_default=False,
        ),
    ]
