# Generated by Django 4.2.21 on 2025-07-10 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_tenantapplication_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
