# Generated by Django 4.2.21 on 2025-08-08 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_tenant_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='num_users',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
