# Generated by Django 4.2.21 on 2025-08-09 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_subscriptiontype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenantapplication',
            name='subscription_plan',
        ),
        migrations.RemoveField(
            model_name='tenantapplication',
            name='subscription_status',
        ),
        migrations.AddField(
            model_name='tenant',
            name='subscription_plan',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.subscriptiontype'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='subscription_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
    ]
