# Generated by Django 4.2.21 on 2025-08-18 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0009_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantapplication',
            name='email',
            field=models.EmailField(help_text='Enter a valid email address.', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='tenantapplication',
            name='slug',
            field=models.SlugField(help_text='Short name used in the URL. Can only contain lowercase letters, numbers and hyphens.', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='tenantapplication',
            name='username',
            field=models.CharField(help_text='Required. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True),
        ),
    ]
