# Generated by Django 5.1.7 on 2025-04-04 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_customuser_smtp_email_customuser_smtp_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
        migrations.AddField(
            model_name='customuser',
            name='position',
            field=models.CharField(blank=True, choices=[('BDA', 'Business Development Assistant'), ('BDM', 'Business Development Manager')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='roles',
            field=models.ManyToManyField(blank=True, to='documents.role'),
        ),
    ]
