# Generated by Django 5.1.7 on 2025-04-19 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_role_remove_customuser_role_customuser_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('approval', 'Approval Letter'), ('sla', 'SLA Document'), ('upload', 'Upload Your Own Document')], max_length=20),
        ),
    ]
