# Generated by Django 5.1.7 on 2025-04-19 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_alter_document_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('approval', 'Approval Letter'), ('sla', 'SLA Document'), ('Uploaded', 'Uploaded Document')], max_length=20),
        ),
    ]
