# Generated by Django 5.1.7 on 2025-04-22 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_alter_document_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_source',
            field=models.CharField(choices=[('template', 'Use Template'), ('upload', 'Upload Document'), ('editor', 'Created in Editor')], default='template', max_length=20),
        ),
    ]
