# Generated by Django 5.1.7 on 2025-05-16 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_department_organization_team_staffprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='account_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='account_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='course',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='degree',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='employment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='graduation_year',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='institution',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='official_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
