# Generated by Django 5.1.7 on 2025-05-17 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0013_alter_staffprofile_emergency_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='religion',
            field=models.CharField(blank=True, choices=[('Islam', 'islam'), ('Christianity', 'christianity'), ('Other', 'other')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='sex',
            field=models.CharField(blank=True, choices=[('Male', 'male'), ('Female', 'female')], max_length=10, null=True),
        ),
    ]
