# Generated by Django 5.1.7 on 2025-05-17 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0014_alter_staffprofile_religion_alter_staffprofile_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='religion',
            field=models.CharField(blank=True, choices=[('islam', 'Islam'), ('christianity', 'Christianity'), ('other', 'Other')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='sex',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True),
        ),
    ]
