# Generated by Django 5.1.7 on 2025-05-20 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0015_alter_staffprofile_religion_alter_staffprofile_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
