# Generated by Django 5.1.7 on 2025-05-23 12:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0017_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='today',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
