# Generated by Django 4.2.21 on 2025-06-10 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0020_usernotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='staff_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('staff_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statt_documents', to='documents.staffprofile')),
            ],
        ),
    ]
