# Generated by Django 4.2.21 on 2025-06-10 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0021_staffdocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffdocument',
            name='title',
        ),
        migrations.AddField(
            model_name='staffdocument',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='staffdocument',
            name='document_type',
            field=models.CharField(choices=[('resume', 'Resume'), ('certificate', 'Certificate'), ('id_card', 'ID Card'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='staffdocument',
            name='file',
            field=models.FileField(upload_to='staff_documents/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='staffdocument',
            name='staff_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='documents.staffprofile'),
        ),
    ]
