# Generated by Django 4.2.21 on 2025-06-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0023_meeting_alter_staffdocument_file_meetingparticipant'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='meeting_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
