# Generated by Django 4.2.21 on 2025-06-18 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0025_event_eventparticipant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
