# Generated by Django 4.2.21 on 2025-06-20 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0030_task_completed_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='position',
        ),
        migrations.AddField(
            model_name='customuser',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='documents.department'),
        ),
        migrations.AddField(
            model_name='department',
            name='hod',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hod_department', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='department',
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='documents.department'),
        ),
    ]
