# Generated by Django 4.2.21 on 2025-06-20 22:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0031_remove_customuser_position_customuser_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='documents.team'),
        ),
        migrations.AddField(
            model_name='folder',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='documents.department'),
        ),
        migrations.AddField(
            model_name='folder',
            name='is_main_folder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='folder',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='documents.team'),
        ),
        migrations.AddField(
            model_name='team',
            name='team_leader',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_leader', to=settings.AUTH_USER_MODEL),
        ),
    ]
