# Generated by Django 4.2.21 on 2025-06-20 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0032_customuser_team_folder_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='department',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='is_main_folder',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='team',
        ),
    ]
