# Generated by Django 4.2.21 on 2025-06-21 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0034_remove_customuser_team_publicfolder_customuser_team_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='team',
            new_name='teams',
        ),
    ]
