# Generated by Django 4.2.21 on 2025-06-21 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import documents.models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0036_file_public_folder_file_updated_at_folder_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='uploads/public/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='file',
            name='file_one_folder_type',
        ),
        migrations.RemoveField(
            model_name='file',
            name='public_folder',
        ),
        migrations.RemoveField(
            model_name='file',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='members', to='documents.team'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=documents.models.upload_to_folder),
        ),
        migrations.AlterField(
            model_name='file',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='documents.folder'),
        ),
        migrations.AlterField(
            model_name='file',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publicfile',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_public_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publicfile',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='public_files', to='documents.publicfolder'),
        ),
    ]
