# Generated by Django 4.2.21 on 2025-06-21 13:54

from django.db import migrations, models
import documents.models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0037_publicfile_remove_file_file_one_folder_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicfile',
            name='file',
            field=models.FileField(upload_to=documents.models.upload_to_public_folder),
        ),
    ]
