# Generated by Django 4.2.21 on 2025-06-30 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0039_remove_department_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='documents',
            field=models.ManyToManyField(blank=True, to='documents.file'),
        ),
    ]
