# Generated by Django 4.2.21 on 2025-07-03 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('documents', '0046_alter_customuser_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='roles', to='auth.permission'),
        ),
        migrations.DeleteModel(
            name='RolePermission',
        ),
    ]
