# Generated by Django 4.2.21 on 2025-07-03 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0047_role_permissions_delete_rolepermission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='tenant',
        ),
        migrations.AlterField(
            model_name='Role',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
