# Generated by Django 4.2.21 on 2025-07-09 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_tenantapplication_password'),
        ('documents', '0048_remove_role_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='tenant_profile/')),
                ('description', models.TextField(blank=True, null=True)),
                ('date_founded', models.DateField(blank=True, null=True)),
                ('reg_number', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_details', models.TextField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('num_staff', models.IntegerField(blank=True, null=True)),
                ('num_departments', models.IntegerField(blank=True, null=True)),
                ('num_teams', models.IntegerField(blank=True, null=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to='tenants.tenant')),
            ],
        ),
    ]
