# Generated by Django 4.2.21 on 2025-07-09 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0049_alter_role_name_companyprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='company_name',
            field=models.CharField(default='company', max_length=255),
            preserve_default=False,
        ),
    ]
