# Generated by Django 4.2.21 on 2025-07-30 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0052_alter_contact_updated_by'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='contact',
            name='contact_list_department_or_team_required',
        ),
    ]
