# Generated by Django 4.2.21 on 2025-08-08 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0054_remove_email_attachment_attachment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='smtp_email',
            new_name='zoho_email',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='smtp_password',
            new_name='zoho_password',
        ),
    ]
