# Generated by Django 4.2.21 on 2025-08-13 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0009_payment'),
        ('documents', '0056_payee_payroll_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customuser', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='department',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='team',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notification', to='tenants.tenant'),
        ),
    ]
