# Generated by Django 4.2.21 on 2025-08-19 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0057_alter_customuser_tenant_alter_department_tenant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='documents',
        ),
        migrations.AddField(
            model_name='task',
            name='documents',
            field=models.FileField(null=True, upload_to='task_documents/'),
        ),
    ]
