# Generated by Django 4.2.21 on 2025-08-19 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0058_remove_task_documents_task_documents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='documents',
        ),
        migrations.AddField(
            model_name='task',
            name='documents',
            field=models.ManyToManyField(blank=True, to='documents.publicfile'),
        ),
    ]
