# Generated by Django 4.2.21 on 2025-08-21 05:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0061_remove_task_folder_remove_task_assigned_to_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='bcc',
        ),
        migrations.RemoveField(
            model_name='email',
            name='cc',
        ),
        migrations.RemoveField(
            model_name='email',
            name='to',
        ),
        migrations.AddField(
            model_name='email',
            name='bcc_emails',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='email',
            name='cc_emails',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='email',
            name='to_emails',
            field=models.TextField(default='faithosebi01@gmail.com'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, help_text='Select staff to assign this task to', null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(help_text='Any notes or details about the task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='documents',
            field=models.ManyToManyField(blank=True, help_text='Attach documents for this task from Public Files', to='documents.publicfile'),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, help_text='Set a due date for the task', null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='pending', help_text='Current status of the task', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(help_text='Required. Title of the task', max_length=255),
        ),
    ]
