# Generated by Django 4.2.21 on 2025-08-21 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0010_alter_tenantapplication_email_and_more'),
        ('documents', '0062_remove_email_bcc_remove_email_cc_remove_email_to_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='publicfolder',
            name='public_folder_department_or_team_required',
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('tenant', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('tenant', 'name')},
        ),
    ]
