# Generated by Django 4.2.21 on 2025-08-22 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0010_alter_tenantapplication_email_and_more'),
        ('documents', '0063_remove_publicfolder_public_folder_department_or_team_required_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffdocument',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_document', to='tenants.tenant'),
        ),
    ]
