# Generated by Django 4.2.21 on 2025-08-22 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0010_alter_tenantapplication_email_and_more'),
        ('documents', '0064_alter_staffdocument_tenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='company_documents/')),
                ('document_type', models.CharField(choices=[('certificate', 'Certificate'), ('contract', 'Contract'), ('license', 'License'), ('memorandum', 'Memorandum'), ('other', 'Other')], default='other', max_length=50)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('company_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='documents.companyprofile')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_document', to='tenants.tenant')),
            ],
        ),
    ]
