# Generated by Django 4.2.21 on 2025-08-23 06:12

from django.db import migrations, models
import uuid

def generate_unique_share_tokens(apps, schema_editor):
    # Get the PublicFile model from the historical schema
    PublicFile = apps.get_model('documents', 'PublicFile')
    # Update all existing PublicFile records with unique share_token values
    for public_file in PublicFile.objects.all():
        public_file.share_token = uuid.uuid4()
        public_file.save()

class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0065_companydocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='PublicFile',
            name='is_shared',
            field=models.BooleanField(default=False, help_text='Enable external sharing for this file'),
        ),
        migrations.AddField(
            model_name='PublicFile',
            name='share_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),  # Allow null temporarily
        ),
        migrations.RunPython(
            code=generate_unique_share_tokens,
            reverse_code=migrations.RunPython.noop,  # No-op for reverse migration
        ),
        migrations.AlterField(
            model_name='PublicFile',
            name='share_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),  # Remove null=True
        ),
    ]
