# Generated by Django 4.2.21 on 2025-08-23 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0066_publicfile_is_shared_publicfile_share_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicfile',
            name='shared_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_public_files', to=settings.AUTH_USER_MODEL),
        ),
    ]
