# Generated by Django 4.2.21 on 2025-08-23 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0067_publicfile_shared_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='attachments',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.DeleteModel(
            name='Attachment',
        ),
    ]
