# Generated by Django 4.2.21 on 2025-09-15 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0069_remove_email_attachments_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='hod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hod', to=settings.AUTH_USER_MODEL),
        ),
    ]
