# Generated by Django 4.2.21 on 2025-09-03 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0069_remove_email_attachments_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='file',
            name='is_shared',
            field=models.BooleanField(default=False, help_text='Enable external sharing for this file'),
        ),
        migrations.AddField(
            model_name='file',
            name='share_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='file',
            name='shared_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_files', to=settings.AUTH_USER_MODEL),
        ),
    ]
