# Generated by Django 4.2.21 on 2025-09-03 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid

def generate_unique_share_tokens(apps, schema_editor):
    # Get the File model from the historical schema
    file = apps.get_model('documents', 'File')
    # Update all existing File records with unique share_token values
    for f in file.objects.all():
        f.share_token = uuid.uuid4()
        f.save()


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0069_remove_email_attachments_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='file',
            name='is_shared',
            field=models.BooleanField(default=False, help_text='Enable external sharing for this file'),
        ),
        migrations.AddField(
            model_name='file',
            name='share_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),  # Allow null temporarily
        ),
        migrations.AddField(
            model_name='file',
            name='shared_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(
            code=generate_unique_share_tokens,
            reverse_code=migrations.RunPython.noop,  # No-op for reverse migration
        ),
        migrations.AlterField(
            model_name='file',
            name='share_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),  # Remove null=True
        ),
        migrations.AlterField(
            model_name='file',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
