# Generated by Django 4.2.21 on 2025-09-03 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0070_file_is_public_file_is_shared_file_share_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
