# Generated by Django 4.2.21 on 2025-09-13 22:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import documents.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0072_alter_file_folder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicfolder',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='publicfolder',
            name='department',
        ),
        migrations.RemoveField(
            model_name='publicfolder',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='publicfolder',
            name='team',
        ),
        migrations.RemoveField(
            model_name='publicfolder',
            name='tenant',
        ),
        migrations.AddField(
            model_name='file',
            name='anon_email',
            field=models.EmailField(blank=True, help_text='Email of uploader if anonymous', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='anon_name',
            field=models.CharField(blank=True, help_text='Name of uploader if anonymous', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='anon_phone',
            field=models.CharField(blank=True, help_text='Phone number of uploader if anonymous', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='share_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='share_time_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='folder',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='folder',
            name='is_shared',
            field=models.BooleanField(default=False, help_text='Enable external sharing for this folders.'),
        ),
        migrations.AddField(
            model_name='folder',
            name='share_files',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='folder',
            name='share_subfolders',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='folder',
            name='share_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='folder',
            name='share_time_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='folder',
            name='share_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='folder',
            name='shared_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_folders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to=documents.models.upload_to_email_attachments),
        ),
        migrations.AlterField(
            model_name='companydocument',
            name='file',
            field=models.FileField(upload_to=documents.models.upload_to_company_documents),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=documents.models.upload_to_company_photos),
        ),
        migrations.AlterField(
            model_name='document',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=documents.models.upload_to_documents_pdf),
        ),
        migrations.AlterField(
            model_name='document',
            name='word_file',
            field=models.FileField(upload_to=documents.models.upload_to_documents_word),
        ),
        migrations.AlterField(
            model_name='staffdocument',
            name='file',
            field=models.FileField(upload_to=documents.models.upload_to_staff_documents),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=documents.models.upload_to_staff_photos),
        ),
        migrations.AlterField(
            model_name='task',
            name='documents',
            field=models.ManyToManyField(blank=True, help_text='Attach documents for this task from Public Files', to='documents.file'),
        ),
        migrations.DeleteModel(
            name='PublicFile',
        ),
        migrations.DeleteModel(
            name='PublicFolder',
        ),
    ]
