# Generated by Django 4.2.21 on 2025-09-13 22:43

from django.db import migrations, models
import uuid

def generate_unique_share_tokens(apps, schema_editor):
    # Get the Folder model from the historical schema
    Folder = apps.get_model('documents', 'Folder')
    # Update all existing PublicFile records with unique share_token values
    for folder in Folder.objects.all():
        folder.share_token = uuid.uuid4()
        folder.save()

class Migration(migrations.Migration):
    dependencies = [
        ('documents', '0073_remove_publicfolder_created_by_and_more'),
    ]
    operations = [
        migrations.RunPython(
            code=generate_unique_share_tokens,
            reverse_code=migrations.RunPython.noop,  # No-op for reverse migration
        ),
        migrations.AlterField(
            model_name='folder',
            name='share_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),  # Remove null=True
        ),
    ]
