# Generated by Django 4.2.21 on 2025-09-05 20:49

from django.db import migrations, models
import documents.models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0073_migrate_public_folder_and_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicfile',
            name='file',
            field=models.FileField(upload_to=documents.models.upload_to_folder),
        ),
        migrations.AlterField(
            model_name='task',
            name='documents',
            field=models.ManyToManyField(blank=True, help_text='Attach documents for this task from Public Files', to='documents.file'),
        ),
    ]
