# Generated by Django 4.2.21 on 2025-09-05 19:40

from django.db import migrations
import os

# Stub function to satisfy historical PublicFile model
def upload_to_public_folder(instance, filename):
    folder_name = instance.folder.name if instance.folder else "unassigned"
    return os.path.join('uploads/public', folder_name, filename)

class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0074_alter_publicfile_file_alter_task_documents'),
    ]

    operations = [
        migrations.DeleteModel(name='PublicFolder'),
        migrations.DeleteModel(name='PublicFile'),
    ]
