# Generated by Django 4.2.21 on 2025-09-08 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid

def generate_unique_share_tokens(apps, schema_editor):
    # Get the Folder model from the historical schema
    Folder = apps.get_model('documents', 'Folder')
    # Update all existing PublicFile records with unique share_token values
    for folder in Folder.objects.all():
        folder.share_token = uuid.uuid4()
        folder.save()


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0075_delete_publicfolder_publicfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='uploaded_by_anonymous',
            field=models.CharField(blank=True, help_text='Name or email of uploader if anonymous', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='folder',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='folder',
            name='is_shared',
            field=models.BooleanField(default=False, help_text='Enable external sharing for this folders.'),
        ),
        migrations.AddField(
            model_name='folder',
            name='share_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='folder',
            name='share_time_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='folder',
            name='share_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='folder',
            name='shared_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_folders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='file',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(
            code=generate_unique_share_tokens,
            reverse_code=migrations.RunPython.noop,  # No-op for reverse migration
        ),
        migrations.AlterField(
            model_name='folder',
            name='share_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),  # Remove null=True
        ),
    ]
