# Generated by Django 4.2.21 on 2025-09-10 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0076_file_uploaded_by_anonymous_folder_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='share_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='share_time_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
