# Generated by Django 4.2.21 on 2025-09-11 12:08

from django.db import migrations, models
import documents.models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0077_file_share_time_file_share_time_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to=documents.models.upload_to_email_attachments),
        ),
        migrations.AlterField(
            model_name='companydocument',
            name='file',
            field=models.FileField(upload_to=documents.models.upload_to_company_documents),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=documents.models.upload_to_company_photos),
        ),
        migrations.AlterField(
            model_name='document',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=documents.models.upload_to_documents_pdf),
        ),
        migrations.AlterField(
            model_name='document',
            name='word_file',
            field=models.FileField(upload_to=documents.models.upload_to_documents_word),
        ),
        migrations.AlterField(
            model_name='staffdocument',
            name='file',
            field=models.FileField(upload_to=documents.models.upload_to_staff_documents),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=documents.models.upload_to_staff_photos),
        ),
    ]
