# Generated by Django 4.2.21 on 2025-09-13 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0078_alter_attachment_file_alter_companydocument_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='uploaded_by_anonymous',
        ),
        migrations.AddField(
            model_name='file',
            name='anon_email',
            field=models.EmailField(blank=True, help_text='Email of uploader if anonymous', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='anon_name',
            field=models.CharField(blank=True, help_text='Name of uploader if anonymous', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='anon_phone',
            field=models.CharField(blank=True, help_text='Phone number of uploader if anonymous', max_length=20, null=True),
        ),
    ]
