# Generated by Django 4.2.21 on 2025-09-13 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0079_remove_file_uploaded_by_anonymous_file_anon_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='share_files',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='folder',
            name='share_subfolders',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
